language: python
python:
  - "2.6"
  - "2.7"
script:
  - cd -
  - cd adagios
  - python manage.py test
install:
  - whoami
  - sudo apt-get update
  - sudo apt-get install -y nagios3 check-mk-livestatus pnp4nagios python-paramiko
  - sudo usermod travis -G nagios -a
  - sudo chown -R nagios:nagios /etc/nagios3
  - sudo chmod -R 777 /etc/nagios3
  - sudo chmod -R a+rx /var/log/nagios3/
  - sudo mkdir -p /etc/adagios/
  - sudo chown -R travis /etc/adagios/
  - sudo usermod -G www-data nagios
  - sudo sed -i 's/RUN.*/RUN="yes"/' /etc/default/npcd
  # okconfig can only be installed with root privileges:
  - deactivate # first deactivate the current env.
  - rm -r ~/virtualenv/python* # and delete it
  - sudo pip install okconfig # sudo install okconfig
  - virtualenv ~/virtualenv/python --system-site-packages # then reinstall virtualenv with system-site-packages
  - source ~/virtualenv/python/bin/activate
  - python --version && pip --version
  # ..done.
  # continue with package requirements
  - pip install -r requirements.txt
  - pip install -r requirements.tests.txt
  # now build adagios:
  - python setup.py build
  - echo "hack to not trigger error with unittest module discovery (https://travis-ci.org/savoirfairelinux/adagios/builds/31937339)"
  - echo "Only 'develop' doesn't work as Adagios installs files e.g. in /etc/adagios"
  - python setup.py install
  - python setup.py develop
  # hack done.
  - pynag config --append "broker_module=/usr/lib/check_mk/livestatus.o /var/lib/nagios3/rw/livestatus"
  - pynag config --set "process_performance_data=1"
  - pynag config --append "broker_module=/usr/lib/pnp4nagios/npcdmod.o config_file=/etc/pnp4nagios/npcd.cfg"
  - pynag config --set 'nagios_binary="/usr/sbin/nagios3"' --filename /etc/adagios/adagios.conf
  - pynag config --set 'nagios_init="/etc/init.d/nagios3"' --filename /etc/adagios/adagios.conf
  - pynag config --set 'nagios_config="/etc/nagios3/nagios.cfg"' --filename /etc/adagios/adagios.conf
  - mkdir -p /etc/nagios3/adagios
  - pynag config --append cfg_dir=/etc/nagios3/adagios
  - cd /etc/nagios3/
  - mkdir -p okconfig/templates
  - mkdir -p okconfig/examples
  - echo "this is required for adagios:"
  - git config --global user.email "noreply@travis-ci.org"
  - git config --global user.name "Adagios buildbot running inside travis"
  - git init
  - git add .
  - git commit -a -m "Initial commit"
  - sudo service nagios3 reload
  - sudo service npcd start
  - sudo chmod -R 777 /var/lib/nagios3
notifications:
  email: false

